res_id <- c("AdaptationOfWorkplace", "BanOnAllEvents", "ClosDaycare", 
           "ClosDaycarePartial", "ClosHigh", "ClosHighPartial", 
           "ClosPrim", "ClosPrimPartial", "ClosPubAny", 
           "ClosPubAnyPartial", "ClosSec", "ClosSecPartial", 
           "EntertainmentVenues", "EntertainmentVenuesPartial", "GymsSportsCentres", 
           "HotelsAccommodation", "IndoorOver100", "IndoorOver1000", 
           "MasksMandatoryAllSpaces", "MasksMandatoryClosedSpaces", "MasksMandatoryClosedSpacesPartial", 
           "MasksVoluntaryClosedSpacesPartial", "MassGather50", "MassGatherAll", 
           "NonEssentialShops", "NonEssentialShopsPartial", "OutdoorOver1000", 
           "OutdoorOver50", "OutdoorOver500", "PlaceOfWorship", 
           "PlaceOfWorshipPartial", "PrivateGatheringRestrictions", "RegionalStayHomeOrder", 
           "RestaurantsCafes", "SocialCircle", "StayHomeGen", 
           "StayHomeOrder", "StayHomeOrderPartial", "Teleworking", 
           "BanOnAllEventsPartial", "GymsSportsCentresPartial", "IndoorOver500", 
           "MasksMandatoryAllSpacesPartial", "MasksVoluntaryAllSpaces", "MassGather50Partial", 
           "MassGatherAllPartial", "PrivateGatheringRestrictionsPartial", "RestaurantsCafesPartial", 
           "StayHomeGenPartial", "TeleworkingPartial", "AdaptationOfWorkplacePartial",  "ClosureOfPublicTransport",
           "ClosureOfPublicTransportPartial", "IndoorOver50", "StayHomeRiskG", "HotelsAccommodationPartial", "OutdoorOver100",
           "WorkplaceClosures", "WorkplaceClosuresPartial", "MasksVoluntaryAllSpacesPartial","MasksVoluntaryClosedSpaces",
           "StayHomeRiskGPartial", "RegionalStayHomeOrderPartial", "SocialCirclePartial")
          
res_text <- c("Adaptation Of Workplace", "Ban On All Events", "Close Daycare", 
              "Close Daycare Partial", "Close High", "Close High Partial", 
              "Close Primary", "Close Primary Partial", "Close Pubs Any Kind", 
              "Close Pubs Any Kind Partial", "Close Secondary", "Close Secondary Partial", 
              "Entertainment Venues", "Entertainment Venues Partial", "Gyms/Sports Centres", 
              "Hotels Accommodation", "Indoor Over 100", "Indoor Over 1000", 
              "Masks Mandatory All", "Masks Mandatory Closed", "Masks Mandatory Closed Partial", 
              "Masks Voluntary Closed Partial", "Mass Gather 50", "Mass Gather All", 
              "Non-Essential Shops", "Non-Essential Shops Partial", "Outdoor Over 1000", 
              "Outdoor Over 50", "Outdoor Over 500", "Place Of Worship", 
              "Place Of Worship Partial", "Private Gathering Restrictions", "Regional Stay Home Order", 
              "Restaurants Cafes", "Social Circle", "Stay Home General", 
              "Stay Home Order", "Stay Home Order Partial", "Teleworking", 
              "Ban On All Events Partial", "Gyms Sports Centres Partial", "Indoor Over 500", 
              "Masks Mandatory All Partial", "Masks Voluntary All", "Mass Gather 50 Partial", 
              "Mass Gather All Partial", "Private Gathering Partial", "Restaurants Cafes Partial", 
              "Stay Home General Partial", "Teleworking Partial", "Adaptation Of Workplace Partial",  "Closure Of Public Transport",
              "Closure Of Public Transport Partial", "Indoor Over 50", "Stay Home Risk Groups", "Hotels Accommodation Partial", "Outdoor Over 100",
              "Workplace Closures", "Workplace Closures Partial", "Masks Voluntary All Partial","Masks Voluntary Closed",
              "Stay Home Risk Groups Partial", "Regional Stay Home Order Partial", "Social Circle Partial")

res_label <- c("Adaptation of workplaces", "Limit all indoor/outdoor mass/public gatherings", "Closure of educational institutions: daycare or nursery", 
               "Closure of educational institutions: daycare or nursery -partially relaxed measure", "Closure of educational institutions: higher education", "Closure of educational institutions: higher education -partially relaxed measure", 
               "Closure of educational institutions: primary schools", "Closure of educational institutions: primary schools -partially relaxed measure", "Closure of public spaces of any kind (including restaurants, entertainment venues, non-essential shops, partial or full closure of public transport, gyms and sport centers, etc)", "Closure of public spaces of any kind (including restaurants, entertainment venues, non-essential shops, partial or full closure of public transport, gyms and sport centers etc) -partially relaxed measure", "Closure of educational institutions: secondary schools", "Closure of educational institutions: secondary schools -partially relaxed measure", 
               "Closure of entertainment venues", "Closure of entertainment venues-partially relaxed measure", "Closure of gyms/sports centres", 
               "Closure of hotels/accommodation services", "Interventions are in place to limit indoor mass/public gatherings of over 100participants", "Interventions are in place to limit indoor mass/public gatherings of over 1000participants", 
               "Protective mask use in all public spaces on mandatory basis (enforced by law)", "Protective mask use in closed public spaces/transport on mandatory basis (enforced by law)", "Protective mask use in closed public spaces/transport on mandatory basis (enforced by law)-partially relaxed measure", 
               "Protective mask use in closed public spaces/transport on voluntary basis (general recommendation not enforced)", "Mass Gather 50", "Interventions are in place to limit mass/public gatherings (any interventions on mass gatherings up to 1000 participants included)", 
               "Closures of non-essential shops", "Closures of non-essential shops -partially relaxed measure", "Interventions are in place to limit outdoor mass/public gatherings of over 1000participants", 
               "Interventions are in place to limit outdoor mass/public gatherings of over 50participants", "Interventions are in place to limit outdoor mass/public gatherings of over 500participants", "Closure of places of worship", 
               "Closure of places of worship-partially relaxed measure", "Restrictions on private gatherings", "Regional stay-at-home orders for the general population at least in one region(these are enforced and also referred to as 'lockdown')", 
               "Closure of restaurants and cafes/bars", "Social circle/bubble to limit social contacts e.g. to limited number of households", "Stay-at-home recommendations for the general population (which are voluntary or not enforced)", 
               "Stay-at-home orders for the general population (these are enforced and also referred to as 'lockdown')", "Stay-at-home orders for the general population (these are enforced and also referred to as 'lockdown') -partially relaxed measure", "Teleworking recommendation", 
               "Interventions are in place to limit all indoor/outdoor mass/public gatherings-partially relaxed measure", "Closure of gyms/sports centres-partially relaxed measure", "Interventions are in place to limit indoor mass/public gatherings of over 500participants", 
               "Protective mask use in all public spaces on mandatory basis (enforced by law)-partially relaxed measure", "Protective mask use in all public spaces on voluntary basis (general recommendation not enforced)", "Mass Gather 50 Partial", 
               "Interventions are in place to limit mass/public gatherings (any interventions on mass gatherings up to 1000 participants included)-partially relaxed measure", "Restrictions on private gatherings-partially relaxed measure", "Closure of restaurants and cafes/bars-partially relaxed measure", 
               "Stay-at-home recommendations for the general population (which are voluntary or not enforced) -partially relaxed measure", "Teleworking recommendation or workplace closures -partially relaxed measure", "Adaptation of workplaces (e.g. to reduce risk of transmission)-partially relaxed measure",  "Closure of public transport",
               "Closure of public transport-partially relaxed measure", "Interventions are in place to limit indoor mass/public gatherings of over 50participants", "Stay-at-home recommendations for risk groups or vulnerable populations (such as the elderly, people with underlying health conditions, physically disabled people, etc.)", "Closure of hotels/accommodation services-partially relaxed measure", "Interventions are in place to limit outdoor mass/public gatherings of over 100participants",
               "Closures of workplaces", "Closures of workplaces-partially relaxed measure", "Protective mask use in all public spaces on voluntary basis (general recommendation not enforced)-partially relaxed measure","Protective mask use in closed public spaces/transport on voluntary basis (general recommendation not enforced)",
               "Stay-at-home recommendations for risk groups or vulnerable populations (such as the elderly, people with underlying health conditions, physically disabled people, etc.) -partially relaxed measure", "Regional stay-at-home orders for the general population at least in one region (these are enforced and also referred to as 'lockdown')-partially relaxed measure", "Social circle/bubble to limit social contacts e.g. to limited number of households-partially relaxed measure")
rest_table <- as.data.frame(cbind(res_id, res_text, res_label))
