selected_measures <- c("AdaptationOfWorkplace", "ClosDaycare", "ClosDaycarePartial", "ClosHigh", "ClosHighPartial",
                       "ClosPrim", "ClosPrimPartial", "ClosPubAny", "ClosPubAnyPartial", "ClosSec", "ClosSecPartial",
                       "EntertainmentVenues", "EntertainmentVenuesPartial", "GymsSportsCentres", "GymsSportsCentresPartial",
                       "HotelsAccommodation", "IndoorOver100", "IndoorOver1000", "IndoorOver50", "IndoorOver500",
                       "MasksMandatoryAllSpaces", "MasksMandatoryAllSpacesPartial", "MasksMandatoryClosedSpaces",
                       "MasksMandatoryClosedSpacesPartial", "MasksVoluntaryAllSpaces", "MassGatherAll", "MassGatherAllPartial",
                       "NonEssentialShops", "NonEssentialShopsPartial", "OutdoorOver100", "OutdoorOver1000", "OutdoorOver50",
                       "OutdoorOver500", "PlaceOfWorship", "PlaceOfWorshipPartial", "PrivateGatheringRestrictions",
                       "RestaurantsCafes", "RestaurantsCafesPartial", "StayHomeGen", "StayHomeOrder", "StayHomeRiskG",
                       "Teleworking", "TeleworkingPartial")

response_labels <- c(AdaptationOfWorkplace = "Adaptationof workplaces(e.g. to reduce risk of transmission",
                     ClosDaycare = "Closure of educational institutions: daycare or nursery.",
                     ClosDaycarePartial = "Closure of educational institutions: daycare or nursery -partially relaxed measure",
                     ClosHigh = "Closure of educational institutions: higher education.",
                     ClosHighPartial = "Closure of educational institutions: higher education -partially relaxed measure",
                     ClosPrim = "Closure of educational institutions: primary schools.",
                     ClosPrimPartial = "Closure of educational institutions: primary schools -partially relaxed measure",
                     ClosPubAny = "Closure of public spaces of any kind (including restaurants, entertainment venues, non-essential shops, partial or full closure of public transport, gyms and sport centers, etc).",
                     ClosPubAnyPartial = "Closure of public spaces of any kind (including restaurants, entertainment venues, non-essential shops, partial orfull closure of public transport, gyms and sport centers etc) -partially relaxed measure",
                     ClosSec = "Closure of educational institutions: secondary schools.",
                     ClosSecPartial = "Closure of educational institutions: secondary schools -partially relaxed measure",
                     EntertainmentVenues = "Closure of entertainment venues",
                     EntertainmentVenuesPartial = "Closure of entertainment venues-partially relaxed measure",
                     GymsSportsCentres = "Closure of gyms/sports centres",
                     GymsSportsCentresPartial = "Closure of gyms/sports centres-partially relaxed measure",
                     HotelsAccommodation = "Closure of hotels/accommodation services",
                     IndoorOver100 = "Interventions are in place to limit indoor mass/public gatherings of over 100participants",
                     IndoorOver1000 = "Interventions are in place to limit indoor mass/public gatherings of over 1000participants",
                     IndoorOver50 = "Interventions are in place to limit indoor mass/public gatherings of over 50participants",
                     IndoorOver500 = "Interventions are in place to limit indoor mass/public gatherings of over 500participants",
                     MasksMandatoryAllSpaces = "Protective mask use in all public spaces on mandatory basis (enforced by law)",
                     MasksMandatoryAllSpacesPartial = "Protective mask use in all public spaces on mandatory basis (enforced by law)-partially relaxed measure",
                     MasksMandatoryClosedSpaces = "Protective mask use in closedpublic spaces/transport on mandatory basis (enforced by law)",
                     MasksMandatoryClosedSpacesPartial = "Protective mask use in closed public spaces/transport on mandatory basis (enforced by law)-partially relaxed measure",
                     MasksVoluntaryAllSpaces = "Protective mask use in all public spaceson voluntary basis (general recommendation not enforced)",
                     MassGatherAll = "Interventions are in place to limit mass/public gatherings (any interventions on mass gatherings up to 1000 participants included)",
                     MassGatherAllPartial = "Interventions are in place to limit mass/public gatherings (any interventions on mass gatherings up to 1000 participants included)-partially relaxed measure",
                     NonEssentialShops = "Closures of non-essential shops",
                     NonEssentialShopsPartial = "Closures of non-essential shops -partially relaxed measure",
                     OutdoorOver100 = "Interventions are in place to limit outdoor mass/public gatherings of over 100participants",
                     OutdoorOver1000 = "Interventions are in place to limit outdoor mass/public gatherings of over 1000participants",
                     OutdoorOver50 = "Interventions are in place to limit outdoor mass/public gatherings of over 50participants",
                     OutdoorOver500 = "Interventions are in place to limit outdoormass/public gatherings of over 500participants",
                     PlaceOfWorship = "Closure of places of worship",
                     PlaceOfWorshipPartial = "Closure of places of worship-partially relaxed measure",
                     PrivateGatheringRestrictions = "Restrictions on private gatherings",
                     RestaurantsCafes = "Closure of restaurants and cafes/bars",
                     RestaurantsCafesPartial = "Closure of restaurants and cafes/bars-partially relaxed measure",
                     StayHomeGen = "Stay-at-home recommendations for the general population (which are voluntary or not enforced)",
                     StayHomeOrder = "Stay-at-home orders for the general population (these are enforced and also referred to as 'lockdown')",
                     StayHomeRiskG = "Stay-at-home recommendations for risk groups or vulnerable populations (such as the elderly, people with underlying health conditions, physically disabled people, etc.)",
                     Teleworking = "Teleworking recommendation",
                     TeleworkingPartial = "Teleworking recommendation or workplace closures -partially relaxed measure")
